# .github/workflows/ci.yml
name: CI

on: 
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Print confirmation
        run: echo "Workflow is running!"